### ISSUE TITLE
how to get ground truth dataset from overwatch

### ISSUE THREAD

**Issue by zhangzheyu2simple** [HarrisonKeeling/overwatch-aimbot#1]
I am trying to train a object detection model on ow too, and wonder how to get the ground truth from overwatch, like the location of objects in ow.

**Comment by HarrisonKeeling** [comment]
There's no simple approach to doing so, but there exist likely a couple approaches I can think of:
1. Transport Layer
2. Application Layer

In the transport layer, you'd need to act as a MITM to possibly obtain the physics vectors of other characters and items in-game;  this may require obtaining unencrypted UDP data through reverse engineering or writing an OS layer tool to sift the unencrypted data.

For the application layer approach, one would need to somehow obtain sidecar access to the rendering lifecycle of the game... this would require some novel approach to reverse engineering their proprietary game engine.
